services:
  tf:
    image: hashicorp/terraform:1.13.3
    working_dir: /tf-code
    volumes:
      - ./setup:/tf-code/setup
      - ./infra:/tf-code/deploy
      - ~/.aws:/root/.aws:ro
    environment:
      - TF_WORKSPACE=${TF_WORKSPACE:-}
